version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8822:80"
        container_name: task_tracker_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: task_tracker_app
        depends_on:
            - db
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5433:5432
        container_name: task_tracker_db
    db_testing:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        ports:
            - 5434:5432
        container_name: task_tracker_db_testing
    redis:
        image: redis:latest
        hostname: 'redis'
        restart: always
        command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
        volumes:
            - redis:/root/redis
            - ./_docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 6382:6379
        container_name: task_tracker_redis
volumes:
    pgdata:
    redis:
